[book]
src = 'src'
title = 'Prophet'
authors = ['Prophet', 'Wonderland']
description = ''
language = 'en'

[output.html]
copy-fonts = false # avoid copying default fonts to book
theme = 'src/prophet-theme'
additional-css = ['src/prophet-theme/css/fonts.css', 'src/prophet-theme/css/colors.css', 'src/prophet-theme/css/base.css']
additional-js = ['src/prophet-theme/js/theme.js', 'src/prophet-theme/js/base.js', 'src/prophet-theme/js/solidity.min.js']
git-repository-url = 'https://github.com/defi-wonderland/prophet-core'
git-repository-icon = 'fa-github'
no-section-label = true
mathjax-support = true

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1        # the depth to start folding
