name: Interface Exporter Action - Production

on:
  push:
    branches:
      - main

jobs:
  generate-and-publish-interfaces:
    if: github.repository == 'defi-wonderland/prophet-core'
    name: Generate Interfaces
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typing_type: ["web3-v1", "ethers-v6", "abi", "contracts"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build project and generate out directory
        run: yarn build

      - name: Export Interfaces - ${{ matrix.typing_type }}
        uses: defi-wonderland/interface-exporter-action@v1.2.2
        with:
          out_dir: "out"
          interfaces_dir: "solidity/interfaces"
          contracts_dir: "solidity/contracts"
          typing_type: "${{ matrix.typing_type }}"
          package_name: "@defi-wonderland/prophet-core-${{ matrix.typing_type }}"
          destination_dir: "exported-interfaces/prophet-core-${{ matrix.typing_type }}"

      - name: Publish
        run: cd exported-interfaces/prophet-core-${{ matrix.typing_type }} && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
